# Tensores

Tensor é a principal estrutura de dados utilizada em um framework de deep learning, simplificadamente podemos dizer que o que o pytorch faz é realizar operações sobre os tensores.
Tensores são um containner para dados, no nosso caso dados númericos, você pode pensar em tensores como uma generalização de matries e vetores, assim, um escalar seria um tensor de rank 0, um vetor um tensor de rank 1 e uma matriz um tensor de rank 2.
Rank é termo utilizado pelos framworks de deep learning para se referir a dimensão do tensor, ou seja, quantos eixos tem um tensor, uma matriz de duas dimensões tem dois eixos.

### Importando PyTorch

In [2]:
import torch

## Criando tensores

O PyTorch utiliza sua propria biblioteca de tensores, porque ele acelera as operações de tensores utilizando GPU, no entanto se você está acostumado com o numpy, converter os tensores do PyTorch para numpy ou vice e versa é muito fácil

In [3]:
torch.tensor([[1., -1.], [1., -1.]])

tensor([[ 1., -1.],
        [ 1., -1.]])

In [5]:
import numpy as np

# tensor do pytorch a partir de um tensor do numpy
torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]))

tensor([[1, 2, 3],
        [4, 5, 6]])

In [6]:
# Tensores com números aleatorios
torch.rand(2,4)

tensor([[0.7361, 0.9944, 0.1003, 0.6392],
        [0.8524, 0.6793, 0.7452, 0.3529]])