# Tensores

Tensor é a principal estrutura de dados utilizada em um framework de deep learning, simplificadamente podemos dizer que o que o pytorch faz é realizar operações sobre os tensores.
Tensores são um containner para dados, no nosso caso dados númericos, você pode pensar em tensores como uma generalização de matrizes e vetores, assim, um escalar seria um tensor com 0 eixos, um vetor um tensor de 1 eixo e uma matriz um tensor de 2 eixos.

Os tensores tem 3 atributos principais:
* **Rank**: o número de eixos que o tensor tem, por exemplo, um tensor de 3 dimensões tem rank 3, pois tem três eixos.
* **Shape**: é representado por uma tupla de inteiros que descreve quantas dimensões o tensor possui ao longo de cada eixo, por exemplo, uma matriz de 2 dimensões tem shape (3, 5), isso quer dizer que ela possui 3 linhas e 5 colunas.
* **Type**: é o tipo do tensor, por exemplo, um tensor pode ser composto de inteiro de 32 bits com sinal, sem sinal, pontos flutuante, e assim por diante, para ver a lista dos tipos suportados pelo pytorch acesse o link: https://pytorch.org/docs/stable/tensors.html

### Importando PyTorch

In [2]:
import torch

## Criando tensores

O PyTorch utiliza sua propria biblioteca de tensores, porque ele acelera as operações de tensores utilizando GPU, no entanto se você está acostumado com o numpy, converter os tensores do PyTorch para numpy ou vice e versa é muito fácil.

#### A partir de lista do python

In [7]:
torch.tensor([[1., -1.], [1., -1.]])

tensor([[ 1., -1.],
        [ 1., -1.]])

In [8]:
# especifica tipo de dados do tensor
torch.tensor([[1., -1.], [1., -1.]], dtype=torch.int32)

tensor([[ 1, -1],
        [ 1, -1]], dtype=torch.int32)

#### A partir de tensores do numpy

In [4]:
import numpy as np

# tensor do pytorch a partir de um tensor do numpy
torch.tensor(np.array([[1, 2, 3], [4, 5, 6]]))

tensor([[1, 2, 3],
        [4, 5, 6]])

#### Tensores de números aleatórios

In [5]:
# Tensores com números aleatorios
torch.rand(2,4)

tensor([[0.9281, 0.8003, 0.2606, 0.0880],
        [0.2624, 0.6398, 0.6265, 0.9890]])

In [6]:
# Tensores aleatórios com semente, para reproduzir mesma sequência pseudoaleatória
torch.manual_seed(123456)
torch.rand(2,4)

tensor([[0.5043, 0.8178, 0.4798, 0.9201],
        [0.6819, 0.6900, 0.6925, 0.3804]])

#### Tensores de zeros

In [9]:
torch.zeros([2, 4], dtype=torch.int32)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

#### Tensores de uns

In [10]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

#### Matriz identidade

In [11]:
torch.eye(4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

#### Tensores na gpu

In [12]:
if torch.cuda.is_available():
    cuda0 = torch.device('cuda:0')
    torch.ones([2, 4], dtype=torch.float64, device=cuda0)

## Operações com tensores

#### visualizando o shape do tensor

In [14]:
t = torch.ones(2,3)
t.size()

torch.Size([2, 3])

#### Modificando o shape do tensor

In [21]:
t1 = torch.ones(4,4)
print(t1.size())
t2 = t1.view(8,2)
print(t2.size())
t3 = t1.view(1, 4,4)
print(t3.size())

torch.Size([4, 4])
torch.Size([8, 2])
torch.Size([1, 4, 4])


Sempre que for modificar o shape de um tensor, observe que a multiplicação do valor da dimensão de cada eixo deve ter sempre o mesmo valor, ou seja
\begin{equation*}4*4 = 8*2 = 1*4*4\end{equation*}

### Conversões entre NumPy e Tensores PyTorch